name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello fellow contributor, feel free to browse around, we are all learning here'' first issue'
        pr-message: 'Great job! Now that you have begin your contributions to this project, feel free to contact me personally at ankushors789@gmail.com'' first pr'
        
    
