name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Compile with Maven
      run: mvn clean compile
    - name: Scope for Maven
      uses: undefinedlabs/scope-for-maven-action@v1
      with:
        # Scope DSN
        #dsn:
        # Flag to indicate if tests must be run. default: true
        run-tests: true # default is true
        # Command to run your tests. default: mvn verify
        command: mvn verify # default is mvn verify
      
  
